#spring:
#  datasource:
#    url: jdbc:mysql://awseb-e-pxwbm5r25n-stack-awsebrdsdatabase-q8laz14mcred.cju0ockocs69.ap-northeast-2.rds.amazonaws.com:3306/board?useSSL=false&serverTimezone=Asia/Seoul
#    username: fastcamp
#    password: Passw0rd
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    open-in-view: true
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        default_batch_fetch_size: 100
##        dialect: org.hibernate.dialect.MySQLDialect
#  cache:
#    type: redis
#    redis:
#      host: awseb-e-pxwbm5r25n-stack-awsebrdsdatabase-q8laz14mcred.cju0ockocs69.ap-northeast-2.rds.amazonaws.com
#      port: 6379
#
#
#
